// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

/**
 * @brief Create the LVGL theme and load the generated Screen1 UI.
 *
 * This function connects the display setup in main.cpp to the objects
 * exported by SquareLine Studio. Without it, the LCD can be ready but the
 * course labels and buttons are not created.
 *
 * @param None.
 * @return Nothing.
 * @call Call once from setup() after the LVGL display has been registered.
 */
void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}

/**
 * @brief Release the generated screen objects.
 *
 * @param None.
 * @return Nothing.
 * @call Call before shutting down or rebuilding the generated UI.
 */
void ui_destroy(void)
{
    ui_Screen1_screen_destroy();
}
