// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui_helpers.h"

/*---------------------------------------------------------------
 * SquareLine Studio helper callbacks
 * These wrappers translate generated UI actions into LVGL calls. The lesson
 * uses the screen and object helpers indirectly through the generated files;
 * the complete set remains available when learners add widgets later.
 *--------------------------------------------------------------*/

/**
 * @brief Apply a generated value action to a bar widget.
 * @param target Bar object to update.
 * @param id Property selector generated by SquareLine Studio.
 * @param val New bar value.
 * @return Nothing.
 * @call Called when a generated event changes a bar property.
 */
void _ui_bar_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_BAR_PROPERTY_VALUE_WITH_ANIM) lv_bar_set_value(target, val, LV_ANIM_ON);
    if(id == _UI_BAR_PROPERTY_VALUE) lv_bar_set_value(target, val, LV_ANIM_OFF);
}

/**
 * @brief Apply a generated position or size action to an LVGL object.
 * @param target Object to update.
 * @param id Position or size property selector.
 * @param val New coordinate or dimension in pixels.
 * @return Nothing.
 * @call Called when a generated event changes basic object geometry.
 */
void _ui_basic_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_BASIC_PROPERTY_POSITION_X) lv_obj_set_x(target, val);
    if(id == _UI_BASIC_PROPERTY_POSITION_Y) lv_obj_set_y(target, val);
    if(id == _UI_BASIC_PROPERTY_WIDTH) lv_obj_set_width(target, val);
    if(id == _UI_BASIC_PROPERTY_HEIGHT) lv_obj_set_height(target, val);
}


/**
 * @brief Select an item in a generated dropdown action.
 * @param target Dropdown object to update.
 * @param id Dropdown property selector.
 * @param val Zero-based item index.
 * @return Nothing.
 * @call Called when a generated event changes dropdown selection.
 */
void _ui_dropdown_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_DROPDOWN_PROPERTY_SELECTED) lv_dropdown_set_selected(target, val);
}

/**
 * @brief Replace the image source used by an image widget.
 * @param target Image object to update.
 * @param id Image property selector.
 * @param val Pointer to the new image source.
 * @return Nothing.
 * @call Called when a generated event changes an image resource.
 */
void _ui_image_set_property(lv_obj_t * target, int id, uint8_t * val)
{
    if(id == _UI_IMAGE_PROPERTY_IMAGE) lv_image_set_src(target, val);
}

/**
 * @brief Replace the text displayed by a label widget.
 * @param target Label object to update.
 * @param id Label property selector.
 * @param val Null-terminated text to display.
 * @return Nothing.
 * @call Called when a generated event changes label text.
 */
void _ui_label_set_property(lv_obj_t * target, int id, const char * val)
{
    if(id == _UI_LABEL_PROPERTY_TEXT) lv_label_set_text(target, val);
}


/**
 * @brief Select a roller item with the generated animation setting.
 * @param target Roller object to update.
 * @param id Roller property selector.
 * @param val Zero-based item index.
 * @return Nothing.
 * @call Called when a generated event changes roller selection.
 */
void _ui_roller_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM) lv_roller_set_selected(target, val, LV_ANIM_ON);
    if(id == _UI_ROLLER_PROPERTY_SELECTED) lv_roller_set_selected(target, val, LV_ANIM_OFF);
}

/**
 * @brief Set a slider value with the generated animation setting.
 * @param target Slider object to update.
 * @param id Slider property selector.
 * @param val New slider value.
 * @return Nothing.
 * @call Called when a generated event changes a slider value.
 */
void _ui_slider_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_SLIDER_PROPERTY_VALUE_WITH_ANIM) lv_slider_set_value(target, val, LV_ANIM_ON);
    if(id == _UI_SLIDER_PROPERTY_VALUE) lv_slider_set_value(target, val, LV_ANIM_OFF);
}


/**
 * @brief Create a target screen when needed and load it with animation.
 * @param target Address of the target screen handle.
 * @param fademode LVGL screen transition type.
 * @param spd Transition duration in milliseconds.
 * @param delay Delay before the transition in milliseconds.
 * @param target_init Function that creates the target screen.
 * @return Nothing.
 * @call Called when a generated navigation event changes screens.
 */
void _ui_screen_change(lv_obj_t ** target, lv_screen_load_anim_t fademode, int spd, int delay,
                       void (*target_init)(void))
{
    if(*target == NULL)
        target_init();
    lv_screen_load_anim(*target, fademode, spd, delay, false);
}

/**
 * @brief Run a generated screen-destroy callback when it is available.
 * @param target Function that destroys the screen.
 * @return Nothing.
 * @call Called after a generated screen transition no longer needs a screen.
 */
void _ui_screen_delete(void (*target)(void))
{
    if(target != NULL) {
        target();
    }
}

/**
 * @brief Add an offset to an arc and report its value change.
 * @param target Arc object to update.
 * @param val Signed value offset.
 * @return Nothing.
 * @call Called by generated arc increment actions.
 */
void _ui_arc_increment(lv_obj_t * target, int val)
{
    int old = lv_arc_get_value(target);
    lv_arc_set_value(target, old + val);
    lv_obj_send_event(target, LV_EVENT_VALUE_CHANGED, 0);
}

/**
 * @brief Add an offset to a bar value.
 * @param target Bar object to update.
 * @param val Signed value offset.
 * @param anm LVGL animation setting.
 * @return Nothing.
 * @call Called by generated bar increment actions.
 */
void _ui_bar_increment(lv_obj_t * target, int val, int anm)
{
    int old = lv_bar_get_value(target);
    lv_bar_set_value(target, old + val, anm);
}

/**
 * @brief Add an offset to a slider and report its value change.
 * @param target Slider object to update.
 * @param val Signed value offset.
 * @param anm LVGL animation setting.
 * @return Nothing.
 * @call Called by generated slider increment actions.
 */
void _ui_slider_increment(lv_obj_t * target, int val, int anm)
{
    int old = lv_slider_get_value(target);
    lv_slider_set_value(target, old + val, anm);
    lv_obj_send_event(target, LV_EVENT_VALUE_CHANGED, 0);
}

/**
 * @brief Attach an on-screen keyboard to a text area.
 * @param keyboard Keyboard object.
 * @param textarea Text area that receives typed characters.
 * @return Nothing.
 * @call Called when generated UI navigation focuses a text field.
 */
void _ui_keyboard_set_target(lv_obj_t * keyboard, lv_obj_t * textarea)
{
    lv_keyboard_set_textarea(keyboard, textarea);
}

/**
 * @brief Add, remove, or toggle an LVGL object flag.
 * @param target Object whose flags are changed.
 * @param flag LVGL flag bit to modify.
 * @param value Generated add, remove, or toggle operation.
 * @return Nothing.
 * @call Called when a generated event changes object behavior.
 */
void _ui_flag_modify(lv_obj_t * target, int32_t flag, int value)
{
    if(value == _UI_MODIFY_FLAG_TOGGLE) {
        if(lv_obj_has_flag(target, flag)) lv_obj_remove_flag(target, flag);
        else lv_obj_add_flag(target, flag);
    }
    else if(value == _UI_MODIFY_FLAG_ADD) lv_obj_add_flag(target, flag);
    else lv_obj_remove_flag(target, flag);
}
/**
 * @brief Add, remove, or toggle an LVGL object state.
 * @param target Object whose state is changed.
 * @param state LVGL state bit to modify.
 * @param value Generated add, remove, or toggle operation.
 * @return Nothing.
 * @call Called when a generated event changes object appearance or behavior.
 */
void _ui_state_modify(lv_obj_t * target, int32_t state, int value)
{
    if(value == _UI_MODIFY_STATE_TOGGLE) {
        if(lv_obj_has_state(target, state)) lv_obj_remove_state(target, state);
        else lv_obj_add_state(target, state);
    }
    else if(value == _UI_MODIFY_STATE_ADD) lv_obj_add_state(target, state);
    else lv_obj_remove_state(target, state);
}


/**
 * @brief Move a text-area cursor and keep the text area focused.
 * @param target Text area to update.
 * @param val Generated cursor direction selector.
 * @return Nothing.
 * @call Called by generated keyboard navigation actions.
 */
void _ui_textarea_move_cursor(lv_obj_t * target, int val)

{

    if(val == UI_MOVE_CURSOR_UP) lv_textarea_cursor_up(target);
    if(val == UI_MOVE_CURSOR_RIGHT) lv_textarea_cursor_right(target);
    if(val == UI_MOVE_CURSOR_DOWN) lv_textarea_cursor_down(target);
    if(val == UI_MOVE_CURSOR_LEFT) lv_textarea_cursor_left(target);
    lv_obj_add_state(target, LV_STATE_FOCUSED);
}

typedef void (*screen_destroy_cb_t)(void);

/**
 * @brief Destroy a screen after LVGL reports that it was unloaded.
 * @param e Event carrying the screen-destroy function in user data.
 * @return Nothing.
 * @call LVGL calls this callback when a generated screen unloads.
 */
void scr_unloaded_delete_cb(lv_event_t * e)

{

    // Get the destroy callback from user_data

    screen_destroy_cb_t destroy_cb = lv_event_get_user_data(e);
    if(destroy_cb) {

        destroy_cb();  // call the specific screen destroy function

    }

}

/**
 * @brief Set the base opacity of an LVGL object.
 * @param target Object to update.
 * @param val Opacity from transparent to opaque.
 * @return Nothing.
 * @call Called by generated opacity actions.
 */
void _ui_opacity_set(lv_obj_t * target, int val)
{
    lv_obj_set_style_opa(target, val, 0);
}

/**
 * @brief Release data allocated for a generated animation.
 * @param a Animation whose user data is released.
 * @return Nothing.
 * @call LVGL calls this callback when the animation is deleted.
 */
void _ui_anim_callback_free_user_data(lv_anim_t * a)
{
    lv_free(a->user_data);
    a->user_data = NULL;
}

/**
 * @brief Apply an animation step to an object's horizontal position.
 * @param a Animation containing the target object in user data.
 * @param v New x coordinate in pixels.
 * @return Nothing.
 * @call LVGL calls this function for each x-position animation step.
 */
void _ui_anim_callback_set_x(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_x(usr->target, v);

}


/**
 * @brief Apply an animation step to an object's vertical position.
 * @param a Animation containing the target object in user data.
 * @param v New y coordinate in pixels.
 * @return Nothing.
 * @call LVGL calls this function for each y-position animation step.
 */
void _ui_anim_callback_set_y(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_y(usr->target, v);

}


/**
 * @brief Apply an animation step to an object's width.
 * @param a Animation containing the target object in user data.
 * @param v New width in pixels.
 * @return Nothing.
 * @call LVGL calls this function for each width animation step.
 */
void _ui_anim_callback_set_width(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_width(usr->target, v);

}


/**
 * @brief Apply an animation step to an object's height.
 * @param a Animation containing the target object in user data.
 * @param v New height in pixels.
 * @return Nothing.
 * @call LVGL calls this function for each height animation step.
 */
void _ui_anim_callback_set_height(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_height(usr->target, v);

}


/**
 * @brief Apply an animation step to an object's opacity.
 * @param a Animation containing the target object in user data.
 * @param v New opacity value.
 * @return Nothing.
 * @call LVGL calls this function for each opacity animation step.
 */
void _ui_anim_callback_set_opacity(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_style_opa(usr->target, v, 0);

}


/**
 * @brief Apply an animation step to an image scale value.
 * @param a Animation containing the image object in user data.
 * @param v New LVGL image scale value.
 * @return Nothing.
 * @call LVGL calls this function for each image-scale animation step.
 */
void _ui_anim_callback_set_image_zoom(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_image_set_scale(usr->target, v);

}


/**
 * @brief Apply an animation step to an image rotation value.
 * @param a Animation containing the image object in user data.
 * @param v New LVGL rotation value.
 * @return Nothing.
 * @call LVGL calls this function for each image-rotation animation step.
 */
void _ui_anim_callback_set_image_angle(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_image_set_rotation(usr->target, v);

}


/**
 * @brief Select the image frame for the current animation step.
 * @param a Animation containing the image set in user data.
 * @param v Requested image-frame index.
 * @return Nothing.
 * @call LVGL calls this function for each image-frame animation step.
 */
void _ui_anim_callback_set_image_frame(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    usr->val = v;

    if(v < 0) v = 0;
    if(v >= usr->imgset_size) v = usr->imgset_size - 1;
    lv_image_set_src(usr->target, usr->imgset[v]);
}

/**
 * @brief Read an object's current horizontal position for animation setup.
 * @param a Animation containing the target object in user data.
 * @return Current aligned x coordinate in pixels.
 * @call LVGL calls this function when preparing an x-position animation.
 */
int32_t _ui_anim_callback_get_x(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_x_aligned(usr->target);

}


/**
 * @brief Read an object's current vertical position for animation setup.
 * @param a Animation containing the target object in user data.
 * @return Current aligned y coordinate in pixels.
 * @call LVGL calls this function when preparing a y-position animation.
 */
int32_t _ui_anim_callback_get_y(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_y_aligned(usr->target);

}


/**
 * @brief Read an object's current width for animation setup.
 * @param a Animation containing the target object in user data.
 * @return Current width in pixels.
 * @call LVGL calls this function when preparing a width animation.
 */
int32_t _ui_anim_callback_get_width(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_width(usr->target);

}


/**
 * @brief Read an object's current height for animation setup.
 * @param a Animation containing the target object in user data.
 * @return Current height in pixels.
 * @call LVGL calls this function when preparing a height animation.
 */
int32_t _ui_anim_callback_get_height(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_height(usr->target);

}


/**
 * @brief Read an object's current opacity for animation setup.
 * @param a Animation containing the target object in user data.
 * @return Current LVGL opacity value.
 * @call LVGL calls this function when preparing an opacity animation.
 */
int32_t _ui_anim_callback_get_opacity(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_style_opa(usr->target, 0);

}

/**
 * @brief Read an image's current scale for animation setup.
 * @param a Animation containing the image object in user data.
 * @return Current LVGL image scale value.
 * @call LVGL calls this function when preparing an image-scale animation.
 */
int32_t _ui_anim_callback_get_image_zoom(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_image_get_scale(usr->target);

}

/**
 * @brief Read an image's current rotation for animation setup.
 * @param a Animation containing the image object in user data.
 * @return Current LVGL image rotation value.
 * @call LVGL calls this function when preparing an image-rotation animation.
 */
int32_t _ui_anim_callback_get_image_angle(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_image_get_rotation(usr->target);

}

/**
 * @brief Read the current image-frame index for animation setup.
 * @param a Animation containing the image set in user data.
 * @return Current image-frame index.
 * @call LVGL calls this function when preparing an image-frame animation.
 */
int32_t _ui_anim_callback_get_image_frame(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return usr->val;

}

/**
 * @brief Format an arc value and display it in a label.
 * @param trg Label that receives the formatted text.
 * @param src Arc that supplies the numeric value.
 * @param prefix Text placed before the value.
 * @param postfix Text placed after the value.
 * @return Nothing.
 * @call Called when a generated event links an arc to a label.
 */
void _ui_arc_set_text_value(lv_obj_t * trg, lv_obj_t * src, const char * prefix, const char * postfix)
{
    char buf[_UI_TEMPORARY_STRING_BUFFER_SIZE];

    lv_snprintf(buf, sizeof(buf), "%s%d%s", prefix, (int)lv_arc_get_value(src), postfix);

    lv_label_set_text(trg, buf);
}

/**
 * @brief Format a slider value and display it in a label.
 * @param trg Label that receives the formatted text.
 * @param src Slider that supplies the numeric value.
 * @param prefix Text placed before the value.
 * @param postfix Text placed after the value.
 * @return Nothing.
 * @call Called when a generated event links a slider to a label.
 */
void _ui_slider_set_text_value(lv_obj_t * trg, lv_obj_t * src, const char * prefix, const char * postfix)
{
    char buf[_UI_TEMPORARY_STRING_BUFFER_SIZE];

    lv_snprintf(buf, sizeof(buf), "%s%d%s", prefix, (int)lv_slider_get_value(src), postfix);

    lv_label_set_text(trg, buf);
}
/**
 * @brief Select label text from another object's checked state.
 * @param trg Label that receives the selected text.
 * @param src Object whose checked state is tested.
 * @param txt_on Text shown while the source is checked.
 * @param txt_off Text shown while the source is not checked.
 * @return Nothing.
 * @call Called when a generated event links a checked state to a label.
 */
void _ui_checked_set_text_value(lv_obj_t * trg, lv_obj_t * src, const char * txt_on, const char * txt_off)
{
    if(lv_obj_has_state(src, LV_STATE_CHECKED)) lv_label_set_text(trg, txt_on);
    else lv_label_set_text(trg, txt_off);
}


/**
 * @brief Move a spinbox one step and report its value change.
 * @param target Spinbox object to update.
 * @param val Positive to increment; zero or negative to decrement.
 * @return Nothing.
 * @call Called by generated spinbox step actions.
 */
void _ui_spinbox_step(lv_obj_t * target, int val)

{

    if(val > 0) lv_spinbox_increment(target);

    else lv_spinbox_decrement(target);


    lv_obj_send_event(target, LV_EVENT_VALUE_CHANGED, 0);
}

/**
 * @brief Select a generated theme when theme support is enabled.
 * @param val Generated theme index.
 * @return Nothing.
 * @call Called by a generated theme-switch action.
 */
void _ui_switch_theme(int val)

{

#ifdef UI_THEME_ACTIVE
    ui_theme_set(val);
#endif
}


